/* the full name is this:
His Royal Majesty, the most highly exalted Major General Master Gunnery Sergeant Lieutenant Archduke Señor Mr. Sir Caesar Dr. Rev. Gregothymasbertotholemewbastianeloponstanteenidicterdinandanastasiajosepheenfinnigan de yung o’ van del O’McFitzMacMontgomeryaristophanesozymandiusmaximilianobelladonnabonaventurawolfeschlegelsteinhausenbergerdorffkambakamantetokounmpohigginbothamfleetwoodlovelacecockskisoneziamore XVI Jr. Sr. XVIII Esquire, M.D. the Rotundest, Patriarch of the Northwest, Superanus sui iuris civitatis Vaticanae, the Great Khan, The Lord of Canada, Savior of Taumata­whakatangihanga­koauau­o­tamatea­turi­pukaka­piki­maunga­horo­nuku­pokai­whenua­ki­tana­tahu, traveler from Llanfair­pwllgwyngyll­gogery­chwyrn­drobwll­llan­tysilio­gogo­goch, swimmer of Lake Char­gogg­a­gogg­man­chaugg­a­gogg­chau­bun­a­gung­a­maugg, the Prophet, the Warden of the Prison of Life, Veteran of the Lawnchair Rebellion of ‘23, Successor vel Vicarius Principis Apostoli, Avatar, Master of All Four Elements, Reader of the Entire Iliad at https://www.youtube.com/watch?v=-EB94KPTkTY&list=PLD1PyBe8b7R1HwdWGRGWYCqTwKd1tIGM5, taker of acetaminophen
*/

elements.His_Royal_Majesty_the_most_highly_exalted_Major_General_Master_Gunnery_Sergeant_Lieutenant_Archduke_Señor_Mr_Sir_Caesar_Dr_Rev_Gregothymasbertotholemewbastianeloponstanteenidicterdinandanastasiajosepheenfinnigan_de_yung_o_van_del_OMcFitzMacMontgomeryaristophanesozymandiusmaximilianobelladonnabonaventurawolfeschlegelsteinhausenbergerdorffkambakamantetokounmpohigginbothamfleetwoodlovelacecockskisoneziamore_XVI_Jr_Sr_XVIII_Esquire_MD_the_Rotundest_Patriarch_of_the_Northwest_Superanus_sui_iuris_civitatis_Vaticanae_the_Great_Khan_The_Lord_of_Canada_Savior_of_Taumatawhakatangihangakoauauotamateaturipukakapikimaungahoronukupokaiwhenuakitanatahu_traveler_from_Llanfairpwllgwyngyllgogerychwyrndrobwllllantysiliogogogoch_swimmer_of_Lake_Chargoggagoggmanchauggagoggchaubunagungamaugg_the_Prophet_the_Warden_of_the_Prison_of_Life_Veteran_of_the_Lawnchair_Rebellion_of_23_Successor_vel_Vicarius_Principis_Apostoli_Avatar_Master_of_All_Four_Elements_Reader_of_the_Entire_Iliad_at_youtube_link_taker_of_acetaminophen = {
    color: ["#826c4e", "#2b5927", "#d6d6d6", "#7d4a2c"],
    behavior: [
        "M2%1 AND SW:water,salt_water,sugar_water,dirty_water,seltzer,pool_water,primordial_soup%1|M2%2 AND SW:water,salt_water,sugar_water,dirty_water,seltzer,pool_water,primordial_soup%50|M2%1 AND SW:water,salt_water,sugar_water,dirty_water,seltzer,pool_water,primordial_soup%1",
        "M2%10|XX|M2%10",
        "XX|M1%33|XX",
    ],
    category:"life",
	state: "solid",
    reactions: {
        "meat": { elem2:null, chance:0.2, func:behaviors.FEEDPIXEL },
        "grass": { elem2:null, chance:0.1, func:behaviors.FEEDPIXEL },
        "worm": { elem2: "crushed_worm", chance:0.3},
        "cooked_meat": { elem2:null, chance:0.2, func:behaviors.FEEDPIXEL },
        "fish": { elem2:null, chance:0.25, func:behaviors.FEEDPIXEL },
        "rat": { elem2:null, chance:0.05, func:behaviors.FEEDPIXEL },
        "snail": { elem2:null, chance:0.05, func:behaviors.FEEDPIXEL },
        "frog": { elem2:null, chance:0.1, func:behaviors.FEEDPIXEL },
        "slug": { elem2:null, chance:0.1, func:behaviors.FEEDPIXEL },
        "grape": { elem2:null, chance:0.3, func:behaviors.FEEDPIXEL },
        "wheat_seed": { elem2:null, chance:0.4, func:behaviors.FEEDPIXEL },
        "flower_seed": { elem2:null, chance:0.32, func:behaviors.FEEDPIXEL },
        "corn_seed": { elem2:null, chance:0.35, func:behaviors.FEEDPIXEL },
        "corn": { elem2:null, chance:0.4, func:behaviors.FEEDPIXEL },
        "crumb": { elem2:null, chance:0.25, func:behaviors.FEEDPIXEL },
        "potato_seed": { elem2:null, chance:0.4, func:behaviors.FEEDPIXEL },
        "grass_seed": { elem2:null, chance:0.3, func:behaviors.FEEDPIXEL },
        "pumpkin_seed": { elem2:null, chance:0.3, func:behaviors.FEEDPIXEL },
        "pumpkin": { elem2:null, chance:0.1, func:behaviors.FEEDPIXEL },
        "nut": { elem2:null, chance:0.2, func:behaviors.FEEDPIXEL },
        "dead_bug": { elem2:null, chance:0.35, func:behaviors.FEEDPIXEL },
        "bee": { elem2:null, chance:0.2, func:behaviors.FEEDPIXEL },
        "ant": { elem2:null, chance:0.2, func:behaviors.FEEDPIXEL },
        "flea": { elem2:null, chance:0.2, func:behaviors.FEEDPIXEL },
        "termite": { elem2:null, chance:0.2, func:behaviors.FEEDPIXEL },
        "lichen": { elem2:null, chance:0.2, func:behaviors.FEEDPIXEL },
        "oxygen": { elem2:"carbon_dioxide", chance:0.3 },
        "mercury": { elem1:"rotten_meat", chance:0.1 },
        "bleach": { elem1:"rotten_meat", chance:0.1 },
        "infection": { elem1:"rotten_meat", chance:0.025 },
        "uranium": { elem1:"rotten_meat", chance:0.1 },
        "cyanide": { elem1:"rotten_meat", chance:0.1 },
        "chlorine": { elem1:"meat", chance:0.1 },
        "dirty_water": { elem1:"rotten_meat", chance:0.0001 },
    },
    egg: "egg",
    foodNeed: 10,
    temp: 40,
    tempHigh: 75,
    stateHigh: "cooked_meat",
    tempLow: -18,
    stateLow: "frozen_meat",
    breakInto: "meat",
    burn:85,
    burnTime:450,
    state: "solid",
    density: 1117,
    conduct: 0.3,
    cutInto: "meat",
}
